fastlane_version "1.35.0"

default_platform :ios

platform :ios do

  before_all do
  end

  desc "Runs all the tests"
  lane :test do
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do

    sigh(
      adhoc: true
    )

    ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]

    xcodebuild_args = {
      PROVISIONING_PROFILE: lane_context[SharedValues::SIGH_UDID],
      PRODUCT_BUNDLE_IDENTIFIER: "d.UIImageEffects"
    }

    xcodebuild_args = xcodebuild_args.map do |k,v|
      "#{k.to_s.shellescape}=#{v.shellescape}"
    end.join ' '

    gym(
      clean: true,
      workspace: 'UIImageEffects.xcodeproj/project.xcworkspace',
      scheme: 'UIImageEffects'
    )

    pilot

  end

  desc "Deploy a new version to the App Store"
  lane :deploy do

    sigh

    ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]

    xcodebuild_args = {
      PROVISIONING_PROFILE: lane_context[SharedValues::SIGH_UDID],
      PRODUCT_BUNDLE_IDENTIFIER: "d.UIImageEffects"
    }

    xcodebuild_args = xcodebuild_args.map do |k,v|
      "#{k.to_s.shellescape}=#{v.shellescape}"
    end.join ' '

    gym(
      clean: true,
      workspace: 'UIImageEffects.xcodeproj/project.xcworkspace',
      scheme: 'UIImageEffects'
    )

    deliver(
      force: true
    )

  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
